name: trsp7

networks:
  app:

services:
  api1:
    build:
      context: ./server1
      dockerfile: Dockerfile
    ports:
      - "10001:10001"
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app

  api2:
    build:
      context: ./server2
      dockerfile: Dockerfile
    ports:
      - "10002:10002"
      - "10003:10003"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: frontend_mirea
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - app

volumes:
  pgdata: